"""
AegisLEO — Sequence Autoencoder Training
==========================================

Created by: Jamie Grunewald
Date: 2026-03-26
Version: v0.1.0

Purpose
-------
Trains a feedforward sequence autoencoder on nominal satellite telemetry.
The model learns to reconstruct normal telemetry windows; at runtime,
reconstruction error above the saved threshold flags anomalous behavior.

Pipeline
--------
1. Load telemetry CSV (generated by models/generate_normal_dataset.py)
2. Build sliding windows via models/window_dataset.py
3. Train SeqAutoencoder (encoder → latent → decoder) to minimize MSE
4. Compute anomaly threshold = mean(errors) + 3 * std(errors) on training set
5. Save model weights → models/seq_autoencoder.pt
6. Save threshold → models/seq_threshold.json

Usage
-----
    # Step 1: generate training data
    python -m models.generate_normal_dataset

    # Step 2: train
    python -m models.train_seq_autoencoder

Outputs are consumed by models/runtime_detector.py during live inference.
Runs on CPU or CUDA (auto-detected). Tested on NVIDIA Jetson Orin Nano Super.
"""

import json
import os

import numpy as np
import torch
import torch.nn as nn
from torch.utils.data import DataLoader, TensorDataset

from models.window_dataset import build_windows

# ── Paths ──────────────────────────────────────────────────────────────
DATA_PATH      = "groundstation/logs/telemetry_normal.csv"
MODEL_PATH     = "models/seq_autoencoder.pt"
THRESHOLD_PATH = "models/seq_threshold.json"

# ── Hyperparameters ────────────────────────────────────────────────────
WINDOW_SIZE = 4    # time steps per sequence window
BATCH_SIZE  = 8
EPOCHS      = 20


# ── Model ──────────────────────────────────────────────────────────────

class SeqAutoencoder(nn.Module):
    """
    Feedforward autoencoder applied across sliding telemetry windows.

    Architecture
    ------------
    Encoder: features → 32 → 16 (latent)
    Decoder: 16 → 32 → features (reconstruction)

    Input shape:  (batch, window_size, features)
    Output shape: (batch, window_size, features)

    Trained with MSE loss on normal data. High reconstruction error
    at inference time indicates anomalous telemetry.
    """

    def __init__(self, features: int) -> None:
        super().__init__()
        self.encoder = nn.Sequential(
            nn.Linear(features, 32),
            nn.ReLU(),
            nn.Linear(32, 16),
        )
        self.decoder = nn.Sequential(
            nn.Linear(16, 32),
            nn.ReLU(),
            nn.Linear(32, features),
        )

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        return self.decoder(self.encoder(x))


# ── Training ───────────────────────────────────────────────────────────

def main() -> None:
    device = "cuda" if torch.cuda.is_available() else "cpu"
    print(f"\nUsing device: {device}")
    if device == "cuda":
        print(f"CUDA device: {torch.cuda.get_device_name(0)}")

    # Load dataset
    print("\nLoading dataset...")
    X = build_windows(DATA_PATH, WINDOW_SIZE)

    if len(X) == 0:
        raise ValueError(
            f"No windows created — dataset too small or missing.\n"
            f"Need more rows than WINDOW_SIZE={WINDOW_SIZE}.\n"
            f"Run: python -m models.generate_normal_dataset"
        )

    print(f"Dataset windows shape: {X.shape}")

    X_tensor = torch.tensor(X, dtype=torch.float32)
    loader = DataLoader(
        TensorDataset(X_tensor, X_tensor),
        batch_size=BATCH_SIZE,
        shuffle=True,
        num_workers=0,
        pin_memory=False,
    )

    # Build model
    features = X_tensor.shape[2]
    model = SeqAutoencoder(features).to(device)
    print("\nModel architecture:")
    print(model)

    optimizer = torch.optim.Adam(model.parameters(), lr=1e-3)
    loss_fn = nn.MSELoss()

    # Training loop
    print("\nStarting training...\n")
    for epoch in range(EPOCHS):
        model.train()
        total_loss = 0.0

        for batch_x, _ in loader:
            batch_x = batch_x.to(device, non_blocking=False)
            optimizer.zero_grad(set_to_none=True)
            pred = model(batch_x)
            loss = loss_fn(pred, batch_x)
            loss.backward()
            optimizer.step()
            total_loss += loss.item()
            del batch_x, pred, loss

        if device == "cuda":
            torch.cuda.empty_cache()

        print(f"Epoch {epoch + 1}/{EPOCHS} → loss={total_loss:.6f}")

    # Compute anomaly threshold
    print("\nComputing anomaly threshold...")
    model.eval()
    with torch.no_grad():
        recon = model(X_tensor.to(device)).cpu().numpy()
        errors = np.mean((X.astype(np.float32) - recon) ** 2, axis=(1, 2))

    threshold = float(np.mean(errors) + 3 * np.std(errors))
    print(f"Threshold: {threshold:.6f}  (mean + 3σ over training set)")

    # Save artifacts
    os.makedirs("models", exist_ok=True)
    torch.save(model.state_dict(), MODEL_PATH)
    with open(THRESHOLD_PATH, "w") as f:
        json.dump({"threshold": threshold}, f, indent=2)

    print(f"\nTraining complete.")
    print(f"  Model     → {MODEL_PATH}")
    print(f"  Threshold → {THRESHOLD_PATH}")
    print(f"\nUpdate config/telemetry.yaml anomaly_threshold: {threshold:.6f}")


if __name__ == "__main__":
    main()
